# site settings
title: Chile Woke Up NZ 🇳🇿 🇨🇱
subtitle:
email:
description: Looking for kiwis awareness and support about abuses of Chile's government
baseurl:
url: https://chilewokeup.github.io
author:
street_address:
city:
state:
zip_code:
country:
phone:
permalink: /:slug

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/unidadsocialakl
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
